"use client";

import { useEffect, useId, useState } from "react";
import { useTheme } from "next-themes";
import { Loader2, TriangleAlert } from "lucide-react";

type MermaidDiagramProps = {
  /** The raw mermaid diagram source (the contents of a ```mermaid block). */
  chart: string;
  /** Use light styling regardless of app theme (browser print / PDF). */
  forceLightTheme?: boolean;
};

type RenderState =
  | { status: "loading" }
  | { status: "done"; svg: string }
  | { status: "error"; message: string };

/** Result tagged with the input it was produced for, so stale renders show as loading. */
type RenderResult = { key: string; state: RenderState };

/**
 * Renders a mermaid diagram from markdown. Mermaid is heavy and browser-only,
 * so it is dynamically imported on first render and kept out of the main bundle.
 * The diagram re-renders when the theme changes so it matches light/dark mode.
 */
export function MermaidDiagram({ chart, forceLightTheme = false }: MermaidDiagramProps) {
  const { resolvedTheme } = useTheme();
  // mermaid.render needs a DOM-id-safe, unique string; useId() contains colons.
  const renderId = `mermaid-${useId().replace(/[^a-zA-Z0-9]/g, "")}`;
  const source = chart.trim();
  const themeKey = forceLightTheme
    ? "light"
    : resolvedTheme === "dark"
      ? "dark"
      : "light";
  // Identifies the exact (theme + source) a result belongs to.
  const renderKey = `${themeKey}::${source}`;
  const [result, setResult] = useState<RenderResult>({
    key: "",
    state: { status: "loading" },
  });

  useEffect(() => {
    if (!source) return;
    let cancelled = false;

    async function render() {
      try {
        // dynamic import → the first await, so the setResult calls below are
        // never synchronous within the effect body.
        const mermaid = (await import("mermaid")).default;
        mermaid.initialize({
          startOnLoad: false,
          securityLevel: "strict",
          theme: forceLightTheme || resolvedTheme !== "dark" ? "default" : "dark",
          fontFamily: "var(--font-geist-sans), system-ui, sans-serif",
        });

        // parse first so syntax errors surface as a clean message, not a throw
        await mermaid.parse(source);
        const { svg } = await mermaid.render(renderId, source);
        if (!cancelled) {
          setResult({ key: renderKey, state: { status: "done", svg } });
        }
      } catch (error) {
        if (cancelled) return;
        const message =
          error instanceof Error ? error.message : "Could not render diagram.";
        setResult({ key: renderKey, state: { status: "error", message } });
      }
    }

    void render();
    return () => {
      cancelled = true;
    };
  }, [source, renderKey, renderId, resolvedTheme, forceLightTheme]);

  if (!source) {
    return null;
  }

  // A result from a previous (theme + source) is stale → keep showing loading.
  const state: RenderState =
    result.key === renderKey ? result.state : { status: "loading" };

  if (state.status === "error") {
    return (
      <div className="not-prose my-4 overflow-hidden rounded-lg border border-destructive/40 bg-destructive/5">
        <div className="flex items-center gap-1.5 border-b border-destructive/30 px-3 py-1.5 text-xs font-medium text-destructive">
          <TriangleAlert className="h-3.5 w-3.5" />
          Diagram error
        </div>
        <p className="px-3 pt-2 text-xs text-destructive/90">{state.message}</p>
        <pre className="m-0 overflow-x-auto bg-transparent p-3 text-xs">
          <code>{source}</code>
        </pre>
      </div>
    );
  }

  if (state.status === "loading") {
    return (
      <div className="not-prose my-4 flex items-center justify-center gap-2 rounded-lg border border-border bg-muted/30 py-10 text-sm text-muted-foreground">
        <Loader2 className="h-4 w-4 animate-spin" />
        Rendering diagram…
      </div>
    );
  }

  return (
    <div
      className="not-prose mermaid-diagram my-4 flex justify-center overflow-x-auto rounded-lg border border-border bg-card p-4"
      // svg is generated by mermaid with securityLevel:"strict" (labels sanitized)
      dangerouslySetInnerHTML={{ __html: state.svg }}
    />
  );
}
